### ISSUE TITLE
Create wireframe of homepage

### ISSUE THREAD

**Issue by MichaelGatesDev** [coding-hub-org/burghy-bites#2]

**Comment by Adora-A** [comment]
![2019-10-06](https://user-images.githubusercontent.com/55360796/66273579-31f36b80-e843-11e9-9ff7-640ac832a3d5.png)

![2019-10-06 (1)](https://user-images.githubusercontent.com/55360796/66273582-3d469700-e843-11e9-97fb-4b780da80721.png)

**Comment by Adora-A** [comment]
![2019-10-06 (2)](https://user-images.githubusercontent.com/55360796/66273640-9f9f9780-e843-11e9-9814-9f4cd639d90d.png)

![2019-10-06 (1)](https://user-images.githubusercontent.com/55360796/66273643-a5957880-e843-11e9-9c82-4a5fbe778c67.png)
